name: Release Client Build
on:
  workflow_dispatch:
jobs:
  native-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps
        run: sudo apt -y install protobuf-compiler lld

      - name: aarch64 setup
        if: contains(matrix.target, 'aarch64')
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib g++-multilib
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt install -y pkg-config libssl-dev

          mkdir -p .cargo
          touch .cargo/config
          printf '[target.aarch64-unknown-linux-gnu]\nlinker = "aarch64-linux-gnu-gcc"' >> .cargo/config

      - name: Install Rust and target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - name: x86_64 setup
        if: contains(matrix.target, 'x86_64')
        run: |
          mkdir -p .cargo
          touch .cargo/config
          printf '[target.x86_64-unknown-linux-gnu]\nrustflags = ["-Clink-arg=-fuse-ld=lld"]' >> .cargo/config

      - name: Install & display rust toolchain
        run: rustup show

      - name: Add aarch64 target
        if: contains(matrix.target, 'aarch64')
        run: rustup target add ${{ matrix.target }}

      - name: Check targets are installed correctly
        run: rustup target list --installed

      - name: Build optimized binary
        run: cargo build --profile production --target ${{ matrix.target }} --locked --bin astar-collator
      - name: Set artifact name
        env:
          TARGET: ${{ matrix.target }}
        id: artifact-name
        run: echo "name=astar-ubuntu-latest-${TARGET%%-*}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: target/${{ matrix.target }}/production/astar-collator
